'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {parsePlaylist,rewriteManifest,webUrl,readableText}=require('../lib/playlist');
test('outside whitespace is ignored without decoding signed URLs or removing path spaces',()=>{assert.equal(webUrl(' \t https://host/path%20one.m3u?token=a%2Fb%2Bc \r\n'),'https://host/path%20one.m3u?token=a%2Fb%2Bc');assert.equal(webUrl(' \u00a0 video%20one.m3u8 \t','https://host/base/list.m3u'),'https://host/base/video%20one.m3u8');assert.throws(()=>webUrl(' \t\n'));});
test('readable labels decode Arabic, percent escapes and HTML entities without executing markup',()=>{assert.equal(readableText('  %D8%A3%D8%AE%D8%A8%D8%A7%D8%B1 &amp; Sport &#x1F4FA;  '),'أخبار & Sport 📺');assert.equal(readableText('100% LIVE'),'100% LIVE');assert.equal(readableText('&lt;script&gt;'),' <script>'.trim());const result=parsePlaylist('#EXTM3U\n#EXTINF:-1 group-title="News%20%26amp%3B%20Sport",Channel%20One\n https://host/a%2Fb?token=%2B123 \n','https://host/list.m3u');assert.equal(result.channels[0].name,'Channel One');assert.equal(result.channels[0].group,'News & Sport');assert.equal(result.channels[0].url,'https://host/a%2Fb?token=%2B123');});
test('provider metadata, relative URLs, Arabic, groups, headers and duplicates',()=>{
 const result=parsePlaylist('\uFEFF#EXTM3U\r\n#EXTINF:-1 tvg-id="one" tvg-logo="logo.png" tvg-language="Arabic" group-title="News, live",أخبار, مباشر\r\n#EXTVLCOPT:http-referrer=https://example.com/\r\n#EXTVLCOPT:http-user-agent=Custom Player\r\nvideo.m3u8\r\n#EXTINF:-1,Duplicate\r\nvideo.m3u8\r\n#EXTINF:-1,Invalid\r\nfile:///secret\r\n','https://example.com/list.m3u');
 assert.equal(result.channels.length,1);assert.equal(result.channels[0].name,'أخبار, مباشر');assert.equal(result.channels[0].group,'News, live');assert.equal(result.channels[0].url,'https://example.com/video.m3u8');assert.equal(result.channels[0].logo,'https://example.com/logo.png');assert.equal(result.channels[0].headers.Referer,'https://example.com/');assert.equal(result.channels[0].language,'Arabic');assert.equal(result.warnings.length,1);
});
test('HLS manifest is a stream, not a channel for each segment',()=>{const parsed=parsePlaylist('#EXTM3U\n#EXT-X-TARGETDURATION:6\n#EXTINF:6,\nvideo.ts\n','https://host/stream.m3u8');assert.equal(parsed.channels.length,1);assert.equal(parsed.channels[0].url,'https://host/stream.m3u8');});
test('nested media, encryption keys and variants are relayed relative to final URL',()=>{const manifest=rewriteManifest('#EXTM3U\n#EXT-X-KEY:METHOD=AES-128,URI="key.bin"\n../segment.ts\n','https://host/live/stream.m3u8',value=>'/relay/'+encodeURIComponent(value));assert.match(manifest,/URI="\/relay\/https%3A%2F%2Fhost%2Flive%2Fkey.bin"/);assert.match(manifest,/\/relay\/https%3A%2F%2Fhost%2Fsegment.ts/);});
test('reject unsupported URLs, HTML and empty playlists',()=>{assert.throws(()=>webUrl('file:///a'));assert.throws(()=>webUrl('http://user:password@host/a'));assert.throws(()=>parsePlaylist('<html>error</html>','http://host'));assert.throws(()=>parsePlaylist('#EXTM3U\n','http://host'));});
test('leading provider comments and plain M3U URL entries are accepted',()=>{const result=parsePlaylist('# Provider notice\n\n#EXTM3U\nvideo.mp4\n#EXTINF:-1,Named\nother.m3u8\n','https://host/list.m3u');assert.equal(result.channels.length,2);assert.equal(result.channels[0].url,'https://host/video.mp4');assert.equal(result.channels[1].name,'Named');});
test('large libraries parse and deduplicate correctly',()=>{const text='#EXTM3U\n'+Array.from({length:10000},(_,i)=>`#EXTINF:-1 group-title="Group ${i%10}",Channel ${i}\nhttps://host/${i}.m3u8`).join('\n');assert.equal(parsePlaylist(text,'https://host/list.m3u').channels.length,10000);});
